new high end piece of software
TotalFreedomMC/TotalFreedomMod pull request #107
Opened 2018-07-29 07:23 UTC by Telesphoreo

- refactor all the shit to isEnabled
- idk debug
- gotta keep the messages consistent
- worldedit :b: roke
- lockup description
- add /nh as an alias for namehistory
- yo /setl actually checks for w/e now cool
- gtfo and unban now are less bugs
- /whitelist is no longer written in tfm43 code and in beta
- l a m b a d a in help
- enable the bridges
- i worked on a converter for the login messages but then seth already made it work so fuck me i wasted an hour of my life
- also can you merge #106

2018-07-29 07:28 UTC, lemonsked requested changes

2018-07-29 07:28 UTC, lemonsked commented on src/main/java/me/totalfreedom/totalfreedommod/command/Command_whitelist.java
> -            return true;
why

2018-07-29 07:28 UTC, lemonsked commented on src/main/java/me/totalfreedom/totalfreedommod/command/Command_whitelist.java
> -            return noPerms();
why

2018-07-29 07:29 UTC, Telesphoreo commented on src/main/java/me/totalfreedom/totalfreedommod/command/Command_whitelist.java
> -            return noPerms();
checkrank

2018-07-29 07:29 UTC, Telesphoreo commented on src/main/java/me/totalfreedom/totalfreedommod/command/Command_whitelist.java
> -            return true;
checkrank

2018-07-29 07:31 UTC, OxLemonxO commented on src/main/java/me/totalfreedom/totalfreedommod/command/Command_whitelist.java
> -            return true;
its the same thing you can just put checkconsole there instead of every switch case

2018-07-29 07:31 UTC, OxLemonxO commented on src/main/java/me/totalfreedom/totalfreedommod/command/Command_whitelist.java
> -            return noPerms();
its the same thing you can just put checke rank there instead of every switch case

2018-07-29 07:32 UTC, Telesphoreo commented on src/main/java/me/totalfreedom/totalfreedommod/command/Command_whitelist.java
> -            return true;
but it still works so who cares

2018-07-29 07:32 UTC, Telesphoreo commented on src/main/java/me/totalfreedom/totalfreedommod/command/Command_whitelist.java
> -            return noPerms();
but it still works so who cares

2018-07-29 07:32 UTC, OxLemonxO commented
also no one even uses whitelist

2018-07-29 07:32 UTC, Telesphoreo commented
cool

its still a command

2018-07-29 07:32 UTC, OxLemonxO commented on src/main/java/me/totalfreedom/totalfreedommod/command/Command_whitelist.java
> -            return true;
you could also say that about it previously

2018-07-29 07:32 UTC, OxLemonxO commented on src/main/java/me/totalfreedom/totalfreedommod/command/Command_whitelist.java
> -            return noPerms();
you could also say that about it previously

2018-07-29 07:33 UTC, Telesphoreo commented on src/main/java/me/totalfreedom/totalfreedommod/command/Command_whitelist.java
> -            return true;
nO bEcAuSe yOu CoUlDn'T puRgE iT

2018-07-29 07:33 UTC, Telesphoreo commented on src/main/java/me/totalfreedom/totalfreedommod/command/Command_whitelist.java
> -            return noPerms();
nO bEcaUSe yOu coUldn'T puRge It

2018-07-29 07:34 UTC, OxLemonxO commented on src/main/java/me/totalfreedom/totalfreedommod/command/Command_whitelist.java
> -            return true;
very important feature!!!

2018-07-29 07:35 UTC, Telesphoreo commented on src/main/java/me/totalfreedom/totalfreedommod/command/Command_whitelist.java
> -            return true;
just like you!!!

2018-07-29 18:15 UTC, script-head requested changes
Do as lemon says

2018-07-30 03:59 UTC, script-head approved these changes

2018-07-30 04:07 UTC, Focusvity commented on src/main/java/me/totalfreedom/totalfreedommod/TotalFreedomMod.java
>          // Disabled so I can at least load TFM as these plugins aren't updated
Maybe remove this line since nothing is disabled.

2018-07-30 07:23 UTC, merged