Update Command_nickclean.java
TotalFreedomMC/TotalFreedomMod pull request #202
Opened 2020-05-27 11:29 UTC by ThePhoenixBlader

https://totalfreedom.boards.net/thread/66931/nickclean-1-person per this suggestion, an option to switch /nickclean to /nickclean <player | -a>

sorry i've never done this before and i already went in game and tested it, works.

2020-05-27 11:33 UTC, Focusvity commented on src/main/java/me/totalfreedom/totalfreedommod/command/Command_nickclean.java
> +        if (args.length == 0)
Why not `args.length != 1`, the command only requires one argument (player name or `-a`)

2020-06-02 01:17 UTC, VideoGameSmash12 commented
sorry for being nitpicky but i think you should update the description of the command to reflect the changes made here

2020-06-02 20:23 UTC, Wild1145 requested changes

2020-06-02 20:23 UTC, Wild1145 commented on src/main/java/me/totalfreedom/totalfreedommod/command/Command_nickclean.java
> +@CommandParameters(description = "Essentials Interface Command - Remove illegal chatcodes from nicknames of all players on server.", usage = "/<command> <player | -a>", aliases = "nc")
No longer is accurately describing what the command does.

2020-06-02 20:23 UTC, Wild1145 commented on src/main/java/me/totalfreedom/totalfreedommod/command/Command_nickclean.java
> +        if (args.length != 1)
Any reason not to default to current behavior?

2020-06-02 20:23 UTC, Wild1145 commented on src/main/java/me/totalfreedom/totalfreedommod/command/Command_nickclean.java
> +            FUtil.adminAction(sender.getName(), "Cleaning " + player.getName() + "'s nickname", false);
Does this need to be broadcasted to all players?

2020-06-14 23:17 UTC, ZeroEpoch1969 commented
Doing this differently. The way I'm doing this is you can optionally specify a specific player, but it defaults to it's original clean all nicknames.

2020-06-14 23:17 UTC, closed without merging